# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file '.\a.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1900, 1000)
        MainWindow.setTabletTracking(False)
        MainWindow.setStyleSheet("background-color: rgb(27, 29, 35);\n""")

        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 221, 1011))
        self.widget.setStyleSheet("background-color: rgb(44, 49, 62);\n"
                "\n"
                "QPushButton {\n"
                "text-algn:left;\n"
                "}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(90, 860, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(50, 850, 31, 31))
        self.label_2.setStyleSheet("border-image: url(./free-icon-font-telegram.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 221, 121))
        self.widget_2.setStyleSheet("\n"
                "#databutton{\n"
                "background-color: #27263c;\n"
                "\n"
                "}")
        self.widget_2.setObjectName("widget_2")
        self.splitter = QtWidgets.QSplitter(self.widget_2)
        self.splitter.setGeometry(QtCore.QRect(20, 20, 201, 91))
        self.splitter.setStyleSheet("#splitter {\n"
                "text-align:left;\n"
                "}\n"
                "QPushButton{\n"
                "border-top-left-radius:10px;\n"
                "border-top-right-radius:10px;\n"
                "border-bottom-left-radius:10px;\n"
                "border-bottom-right-radius:10px;\n"
                "}")
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.databutton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.databutton.setFont(font)
        self.databutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.databutton.setStyleSheet("color: rgb(255, 255, 255);\n"
                "background-color: rgb(27, 29, 35);\n"
                "\n"
                "pushButton_2 {\n"
                "text-align:left;\n"
                "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/free-icon-font-apps.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.databutton.setIcon(icon)
        self.databutton.setObjectName("databutton")
        self.pushButton_3 = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/free-icon-font-edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setGeometry(QtCore.QRect(0, 740, 221, 80))
        self.widget_3.setStyleSheet("QPushButton{\n"
                "border-top-left-radius:10px;\n"
                "border-bottom-left-radius:10px;\n"
                "}")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 50, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/free-icon-font-settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setGeometry(QtCore.QRect(0, 130, 45, 613))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 588, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setGeometry(QtCore.QRect(230, 10, 1661, 1011))
        self.main_widget.setStyleSheet("background-color: rgb(44, 49, 62);\n"
                "QPushButton {\n"
                "border-top-left-radius:10px;\n"
                "border-bottom-radius:10px;\n"
                "}\n"
                "")
        self.main_widget.setObjectName("main_widget")
        self.tableView = QtWidgets.QTableView(self.main_widget)
        self.tableView.setGeometry(QtCore.QRect(30, 90, 1601, 811))
        self.tableView.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableView.setAlternatingRowColors(False)
        self.tableView.setObjectName("tableView")
        self.lineEdit = QtWidgets.QLineEdit(self.main_widget)
        self.lineEdit.setGeometry(QtCore.QRect(630, 20, 371, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
                "QLineEdit {\n"
                "border-top-left-radius:10px;\n"
                "}\n"
                "")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.main_widget)
        self.pushButton.setGeometry(QtCore.QRect(930, 20, 71, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
                                "\n"
                                "QPushButton {\n"
                                "border-top-left-radius:5px\n"
                                "\n"
                                "}")
        self.pushButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1900, 26))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setStyleSheet("color: rgb(255, 255, 255);")
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setGeometry(QtCore.QRect(270, 153, 171, 184))
        self.menuHome.setBaseSize(QtCore.QSize(0, 0))
        self.menuHome.setSeparatorsCollapsible(False)
        self.menuHome.setToolTipsVisible(False)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        self.actionSave.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/check (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionSave.setFont(font)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("./menu-burger.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_as.setIcon(icon5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionSave_as.setFont(font)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionExport_File = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/free-icon-font-download.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport_File.setIcon(icon6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionExport_File.setFont(font)
        self.actionExport_File.setObjectName("actionExport_File")
        self.actionImport_File = QtWidgets.QAction(MainWindow)
        self.actionImport_File.setIcon(icon6)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionImport_File.setFont(font)
        self.actionImport_File.setObjectName("actionImport_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuHome.addAction(self.actionSave)
        self.menuHome.addAction(self.actionSave_as)
        self.menuHome.addAction(self.actionExport_File)
        self.menuHome.addAction(self.actionImport_File)
        self.menuHome.addAction(self.actionExit)
        self.menubar.addAction(self.menuHome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Telegram"))
        self.databutton.setText(_translate("MainWindow", " Database"))
        self.pushButton_3.setText(_translate("MainWindow", " Edit"))
        self.pushButton_4.setText(_translate("MainWindow", " Settings"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as.setShortcut(_translate("MainWindow", "Ctrl+T"))
        self.actionExport_File.setText(_translate("MainWindow", "Export File"))
        self.actionExport_File.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionImport_File.setText(_translate("MainWindow", "Import File"))
        self.actionImport_File.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # ui.buttons()
    MainWindow.show()
    sys.exit(app.exec_())